// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llrumtjljzzhvqfxowpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxscnVtdGpsanp6aHZxZnhvd3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzkzNTIsImV4cCI6MjA2NjUxNTM1Mn0.8Q7v4d_gnfa9ewgq_h3CnLlsWHj6efuAkconKr8nd7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});